### ISSUE TITLE
Infografia Practica 7 de Juan Antonio

### ISSUE THREAD

**Issue by JAntonioCoder** [SistemasTecTlaxiaco/infografia-de-hilos-JAntonioCoder#2]
[Hilos_Infigrafia_Nicolas Perez Juan Antonio.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-JAntonioCoder/files/15044060/Hilos_Infigrafia_Nicolas.Perez.Juan.Antonio.pdf)

**Comment by GerardoNR** [comment]
18
esta bien, solo que no puso ninguna imagen

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
